require('dotenv').config()
const express = require('express')
const app = express()
const cors = require('cors')
app.use(cors())
app.use(express.json())
const userRoutes = require('./Routes/UserRouter')
app.use("/user",userRoutes)
app.listen(process.env.PORT_NUMBER,()=>{
    console.log("Server Active and Listening")
})